### ISSUE TITLE
Connor can not find offsets in topics with many messages

### ISSUE THREAD

**Issue by akohlbecker** [helpermethod/connor#158]
After starting my kafka cluster from scratch and let the 33 source connectors poll for changes a couple of hours the Connor `OffsetResetter` works perfectly.

Some days later the offsets topic (mine is named `_connect-cluster-a-offsets`) holds 112992 messages in 25 Partitions with a segment size of 16MGB. 67000 messages alone for the source connector to be resetted. (33 source connectors in total) In this situation the `OffsetResetter` no longer finds any offset.

Increasing the poll duration to 20 seconds in the `OffsetResetter` (line 52) 

~~~java
var offsets = generate(() -> consumer.poll(Duration.ofSeconds(20)))
~~~

and setting in the `Connor` class an increased value for the consumer `retry.backoff.ms` of 250 ms helps find the offset:

~~~java
    private KafkaConsumer<String, byte[]> createConsumer() {
        var consumerConfig = Map.<String, Object>of(
            ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG,
            bootstrapServers,
            ConsumerConfig.GROUP_ID_CONFIG,
            "connor-" + new Random().nextInt(100_000),
            ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG,
            false,
            ConsumerConfig.AUTO_OFFSET_RESET_CONFIG,
            "earliest",
            ConsumerConfig.RETRY_BACKOFF_MS_CONFIG,
            250
        );
~~~
However the polling runs for ~2 minutes and 15 seconds in this case. From the poll value set in `OffsetResetter` I would expect it to run for 20 s maximum.

I am not sure if there is a problem with my offsets topic having too many massages, or if the timeouts or even the polling strategy of connor need to be improved. Adding an option to start polling at a specific timestamp could improve this a lot. Often you want to reset topic offsets which are far younger than one day.

**Comment by helpermethod** [comment]
Hi @akohlbecker!

I am actually amazed that Connor works at all 😁!

I've written Connor when evaluating Kafka Connect for a company project, but left the company before using it in production.

Does it correctly reset the offset when applied?

If people are using it, I may need to reactivate the project :).

Note that the poll duration only applies for a single poll, and the Kafka client polls records in batches. So to read through all partitions the client will have to poll repeatedly for records until no more records are found.

One idea to improve performance would be to make the batch size configurable (`max.poll.records`).

I wonder how long a single poll would take in your case. Maybe something like a `--verbose` flag which outputs diagnostic messages could help.

**Comment by akohlbecker** [comment]
Hi @helpermethod , connor really works and can reset the offset of source topics. Resetting the offset only is only one of a couple of required steps to permanently reset the topic. The source connector needs to be removed and re-applied:

1. remove source connector
2. reset topic 
3. restore source connector

otherwise most source connectors may not reload the offset from the offsets-topic.

I attempted to extend connor nut was stuck compiling the nativeimage application. Running the final executable it always failed with 

~~~
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:825)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666)
        at com.github.helpermethod.connor.Connor.createConsumer(Connor.java:73)
        at com.github.helpermethod.connor.Connor.run(Connor.java:52)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at com.github.helpermethod.connor.Connor.main(Connor.java:83)
Caused by: org.apache.kafka.common.KafkaException: Could not find a public no-argument constructor for org.apache.kafka.clients.consumer.RangeAssignor
        at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:394)
        at org.apache.kafka.clients.consumer.ConsumerPartitionAssignor.getAssignorInstances(ConsumerPartitionAssignor.java:285)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:771)
        ... 12 more
Caused by: java.lang.NoSuchMethodException: org.apache.kafka.clients.consumer.RangeAssignor.<init>()
        at java.lang.Class.getConstructor0(DynamicHub.java:3585)
        at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2754)
        at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:392)
        ... 14 more
~~~

So I decided to go another way and  implemented the same functionality in a bash script using `kafkacat` - works very reliable and fast until now. So for me there is no longer any need to use connor.

Best wishes
